steps:
- name: "node:10.16.3"
  entrypoint: npm
  args: ['install']

- name: "node:10.16.3"
  entrypoint: npm
  args: ['run', 'test']

- name: "node:10.16.3"
  entrypoint: npm
  args: ['run', 'lint']

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=gcloud-env.yaml.enc
  - --plaintext-file=gcloud-env.yaml
  - --location=global
  - --keyring=build-ring
  - --key=env-enc-key

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - welcome-email
  - --source=.
  - '--trigger-event=providers/firebase.auth/eventTypes/user.create'
  - '--trigger-resource=bookit-app-260021'
  - --runtime=nodejs10
  - --env-vars-file=gcloud-env.yaml
  - --region=us-east1
  - --entry-point=welcomeEmail